export const DISCIPLINE_OPTIONS = [
  "Structural / Civil",
  "Arch / Finishing",
  "Landscape",
  "Mechanical",
  "Electrical",
  "Plumbing",
  "Facade",
  "Others",
];

export const YES_NO_OPTIONS = ["Yes", "No"];

export const EMPTY_MIR = {
  title: "Material Inspection Request (MIR)",
  projectName: "",
  projectCode: "",
  mirRefNo: "",
  materialCode: "",
  requestSubmission: {
    clientEmployer: "",
    clientSubmissionDateTime: "",
    pmc: "",
    engineer: "",
    engineerInspectionDateTime: "",
    contractor: "",
    submittedTo: "",
    vendorCode: "",
    refDocAttached: "",
    discipline: [],
  },
  contractorPart: {
    materialSubmittalApproved: "",
    approvalRefNo: "",
    description: "",
    previousQty: "",
    currentQty: "",
    cumulativeQty: "",
    boqReference: "",
    manufacturerCountry: "",
    supplier: "",
    deliveryNoteNumber: "",
    receiptDate: "",
    storageLocation: "",
    testCertificateDelivered: "",
    fieldTestConducted: "",
    fieldTestComplianceNote: "",
    thirdPartyTestContractorScope: "",
    thirdPartyTestContractorComplianceNote: "",
    thirdPartyTestLodhaScope: "",
    thirdPartyTestLodhaComplianceNote: "",
    contractorName: "",
    contractorSignature: "",
    contractorDate: "",
  },
  lodhaPmc: {
    inspectionReports: {
      physicalDamage: "",
      deliveryNoteCorrect: "",
      conformApprovedSubmittal: "",
      mtcDelivered: "",
      fieldTestCompliance: "",
      thirdPartyContractorScope: "",
      thirdPartyLodhaScope: "",
    },
    signOffs: {
      civilProjectManager: "",
      civilQualityManager: "",
      facadeManager: "",
      landscapeArchitect: "",
      mepManager: "",
    },
    comments: "",
    resultCode: "",
    resultName: "",
    resultSignature: "",
    resultDate: "",
    distribution: {
      lodha: false,
      contractor: false,
      others: "",
    },
  },
  templateRef: "",
  templateRevision: "",
  templateDate: "",
  source: "Manual",
  sourceFileName: "",
};
